storage:
  domain: "api.cookiepang.site"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cooiepang-db.ctsd0extrjqk.ap-northeast-2.rds.amazonaws.com:5432/cookiepang_real

cloud:
  aws:
    s3:
      cdnUrl: "cdn.cookiepang.site"
      bucket: cookiepang
      directory: pictures

contract:
  admin-address: "0xe3F744017BB487F88B1CE9587FfD672E9F306769"
  kas:
    chain-id: "8217"
    node-api-url: "https://node-api.klaytnapi.com/v1/klaytn"
  addr:
    cookie: "0xB8Bad0d120919cb43F8151Da2eeab8089F167282"
    hammer: "0x6203f3F22951B46Dc48847338c2e26D9D2080D73"
  address: 123456
