storage:
  domain: "api.cookiepang.site"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cooiepang-db.ctsd0extrjqk.ap-northeast-2.rds.amazonaws.com:5432/cookiepang_real

cloud:
  aws:
    s3:
      bucket: cookiepang
      directory: pictures

contract:
  admin-address: "0xe3F744017BB487F88B1CE9587FfD672E9F306769"
  kas:
    chain-id: "8217"
    node-api-url: "https://node-api.klaytnapi.com/v1/klaytn"
  addr:
    cookie: "0xC0b8FC7fE268Ae1e874e009F86D74010C3385D59"
    hammer: "0xD6E679cf1c9980203604a57603e79e0660757C8a"
  address: 123456
