package com.ojicoin.cookiepang.config;

// FIXME: 이거 kotlin으로 바꾸면 EOF 에러.. 아예 json 올리고 설정 가져오는 방식으로 바꿔야할듯
public class ContractABI {
	public static final String HAMMER_COIN = "[\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"addMinter\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"addPauser\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"name\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"symbol\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint8\",\n"
		+ "\"name\": \"decimals\",\n"
		+ "\"type\": \"uint8\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"initialSupply\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"constructor\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"spender\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"value\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Approval\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"spender\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"value\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"approve\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"burn\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"burnFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"maxApprove\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"mint\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"MinterAdded\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"MinterRemoved\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"previousOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"newOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"OwnershipTransferred\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"pause\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Paused\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"PauserAdded\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"PauserRemoved\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"renounceMinter\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"renounceOwnership\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"renouncePauser\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"recipient\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransfer\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"recipient\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bytes\",\n"
		+ "\"name\": \"data\",\n"
		+ "\"type\": \"bytes\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransfer\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"sender\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"recipient\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransferFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"sender\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"recipient\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"amount\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bytes\",\n"
		+ "\"name\": \"data\",\n"
		+ "\"type\": \"bytes\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransferFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"_cookieContractAddress\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"setCookieContractAddress\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"value\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"transfer\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"value\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Transfer\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"value\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"transferFrom\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"newOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"transferOwnership\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"unpause\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Unpaused\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"spender\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"allowance\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"balanceOf\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"decimals\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint8\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint8\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"isMinter\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"isOwner\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"account\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"isPauser\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"maxApprovedAddress\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"name\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"owner\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"paused\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bytes4\",\n"
		+ "\"name\": \"interfaceId\",\n"
		+ "\"type\": \"bytes4\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"supportsInterface\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"symbol\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"totalSupply\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "}\n"
		+ "]";

	public static final String COOKIE_FACTORY = "[\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"cofounder\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"addCoFounder\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"approved\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Approval\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"operator\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"approved\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"ApprovalForAll\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"approve\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"burnCookie\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"buyCookie\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_hammerPrice\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"changeHammerPrice\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"uint8\",\n"
		+ "\"name\": \"eventStatus\",\n"
		+ "\"type\": \"uint8\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": false,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"hammerPrice\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"createdAt\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"CookieEvented\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"isHide\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"hideCookie\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_title\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_content\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_imageUrl\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_tag\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_hammerPrice\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"mintCookieByHammer\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_title\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_content\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_imageUrl\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_tag\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_hammerPrice\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"mintCookieByKlaytn\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": true,\n"
		+ "\"stateMutability\": \"payable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"creator\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_title\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_content\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_imageUrl\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"_tag\",\n"
		+ "\"type\": \"string\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_hammerPrice\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"mintCookieByOwner\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"previousOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"newOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"OwnershipTransferred\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"renounceOwnership\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransferFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bytes\",\n"
		+ "\"name\": \"_data\",\n"
		+ "\"type\": \"bytes\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"safeTransferFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"isSale\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"saleCookie\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"approved\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"setApprovalForAll\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_mintingPriceForHammer\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"setMintingPriceForHammer\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"_mintingPriceForKlaytn\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"setMintingPriceForKlaytn\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"contract KIP7Token\",\n"
		+ "\"name\": \"_tradeCurrency\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"setTradeCurrency\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"anonymous\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"indexed\": true,\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"Transfer\",\n"
		+ "\"type\": \"event\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"from\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"to\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"transferFrom\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"newOwner\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"transferOwnership\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"withdraw\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": false,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"withdrawHammer\",\n"
		+ "\"outputs\": [],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"nonpayable\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"balanceOf\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"coFounderAddress\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"cookieHammerPrices\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"getApproved\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"getContent\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"getOwnedCookieIds\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256[]\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256[]\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"hideCookies\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"operator\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"isApprovedForAll\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"isOwner\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"mintingPriceForHammer\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"mintingPriceForKlaytn\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"name\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"owner\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address payable\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"tokenId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"ownerOf\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"address\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"saleCookies\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bytes4\",\n"
		+ "\"name\": \"interfaceId\",\n"
		+ "\"type\": \"bytes4\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"supportsInterface\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"bool\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"bool\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"symbol\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"index\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"tokenByIndex\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"address\",\n"
		+ "\"name\": \"owner\",\n"
		+ "\"type\": \"address\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"index\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"tokenOfOwnerByIndex\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"cookieId\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"name\": \"tokenURI\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"string\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"string\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "},\n"
		+ "{\n"
		+ "\"constant\": true,\n"
		+ "\"inputs\": [],\n"
		+ "\"name\": \"totalSupply\",\n"
		+ "\"outputs\": [\n"
		+ "{\n"
		+ "\"internalType\": \"uint256\",\n"
		+ "\"name\": \"\",\n"
		+ "\"type\": \"uint256\"\n"
		+ "}\n"
		+ "],\n"
		+ "\"payable\": false,\n"
		+ "\"stateMutability\": \"view\",\n"
		+ "\"type\": \"function\"\n"
		+ "}\n"
		+ "]";
}
