name: Gradle Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        env:
          CONTRACT_KAS_ACCESS_KEY_ID: ${{ secrets.CONTRACT_KAS_ACCESS_KEY_ID }}
          CONTRACT_KAS_SECRET_ACCESS_KEY: ${{ secrets.CONTRACT_KAS_SECRET_ACCESS_KEY }}
          CONTRACT_ADMIN_PRIVE_KEY: ${{ secrets.CONTRACT_ADMIN_PRIVE_KEY }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          DATA_SOURCE_USERNAME: ${{ secrets.DATA_SOURCE_USERNAME }}
          DATA_SOURCE_PASSWORD: ${{ secrets.DATA_SOURCE_PASSWORD }}
        run: ./gradlew build -Dspring.profiles.active=dev
